### PR TITLE
react-addons-shallow-compare  -> React.PureComponent

### PR DESCRIPTION
**Pull request by ened**
Remove the legacy addon and replace with PureComponent as discussed here: 
https://facebook.github.io/react/docs/shallow-compare.html

### CODE REVIEW

**Comment by borisyankov** [comment]
Hey, the PR looks good! It is conflicting with our other PR that I just merged. If you rebase I'll merge ASAP.

**Comment by ened** [comment]
@borisyankov done

**Comment by borisyankov** [comment]
Thanks. 👍

**Comment by nbkhope** [comment]
Has the development of `react-sparklines` come to a halt? Since nobody seems to care about fixing the latest release that is broken.

**Pull request merged**
