### PR TITLE
Made sparkline component responsive by default for borisyankov/react-sparklines#49

### PR DESCRIPTION
**Pull request by codecounselor**
Updated documentation and changed default options so that height and width of the SVG element have to be explicitly defined.

### CODE REVIEW

**Comment by motiz88** [comment]
Hey there, a fellow react-sparklines user here.
1. Would you mind elaborating the rationale behind making `height` and `width` required? Isn't there a reasonable default (or implicit value) we could set?
2. I worry that changing the meaning of these existing props may break some code out there more than necessary.

I'm all for separating the viewbox size from the element's size - I just think the defaults should be carefully considered.

**Comment by codecounselor** [comment]
I think I was not clear.  The height and width currently have defaults, and I did not change those.  I added a new set of attributes for the width and height of the SVG element itself.  Those have no defaults, and as such it causes the element to fill the parent element and be responsive.  

I was trying to say that if you want the SVG element to not fill you can set the svgHeight or svgWidth attributes which I just added.

Hope that helps!

**Comment by motiz88** [comment]
@codecounselor Picking up from https://github.com/borisyankov/react-sparklines/issues/49#issuecomment-210463289:
I understand your PR better now and I'm fine with it, personally. I've actually merged this into my personal-use `master` branch and am happy with how it works.

And yes, you'll find that if you merge #48 (or equivalently my branch [`fix-travis`](https://github.com/motiz88/react-sparklines/tree/fix-travis)) into your `master` it will pass CI.

**Comment by DeltaLikeM** [comment]
👍

**Pull request merged**
