### PR TITLE
Replace React.PropTypes with PropTypes

### PR DESCRIPTION
**Pull request by ened**
As outline in https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html and mentioned in #63

### CODE REVIEW

**Comment by calebwoods** [comment]
Was going to submit a PR for this same fix.  Would like to get the warnings removed.  This PR would fix #86

**Comment by jeffvandyke** [comment]
This looks good to me as well, it's a pretty common and simple change in a lot of projects.

**Comment by hampusohlsson** [comment]
+1

**Comment by maxnowack** [comment]
@borisyankov please merge this :)

**Comment by michelegera** [comment]
I’d love to see this merged too. In the meantime, I am using @ened’s fork. 👍 🎩

**Comment by borisyankov** [comment]
Thanks for the contribution @ened

**Pull request merged**
